#!/usr/bin/env python

import subprocess as sp

all_tests = [
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'array_01_decl',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'array_02_decl',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'array_03_decl',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'variable_decl_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'variable_decl_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'variable_decl_03',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'array_expr_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': True,
        'ENABLE_CPYTHON': False,
        'NAME': 'array_expr_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'array_size_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'array_size_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'array_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;wasm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'array_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;wasm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'array_03',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'bindc_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'bindc_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'bindc_04',
        'IMPORT_PATH': '',
        'LABELS': 'llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': True,
        'ENABLE_CPYTHON': False,
        'NAME': 'bindc_07',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'bindc_08',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'bindc_09',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': True,
        'ENABLE_CPYTHON': False,
        'NAME': 'exit_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': True,
        'NOFAST': True,
        'ENABLE_CPYTHON': False,
        'NAME': 'exit_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'exit_03',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x86;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': True,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'exit_04',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x86;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'exit_01b',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x86;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': True,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'exit_02b',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x86;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': True,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'exit_02c',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'print_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'print_03',
        'IMPORT_PATH': '',
        'LABELS': 'x86;c;wasm;wasm_x86;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'print_04',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'print_06',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'print_05',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'print_float',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': True,
        'ENABLE_CPYTHON': False,
        'NAME': 'print_list_tuple_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': True,
        'ENABLE_CPYTHON': False,
        'NAME': 'print_list_tuple_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'const_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'const_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'const_03',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': 'const_03b.c',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'const_04',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'expr_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'expr_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'expr_03',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'expr_04',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'expr_05',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'expr_06',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'expr_07',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'expr_08',
        'IMPORT_PATH': '',
        'LABELS': 'llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'expr_09',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'expr_10',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'expr_11',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'expr_12',
        'IMPORT_PATH': '',
        'LABELS': 'llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'expr_13',
        'IMPORT_PATH': '',
        'LABELS': 'llvm;c',
        'EXTRAFILES': 'expr_13b.c',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'expr_14',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'expr_15',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'expr_16',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'expr_01u',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'expr_02u',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'expr_03u',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'loop_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'loop_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x86;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'loop_03',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'loop_04',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'loop_05',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'if_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x86;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'if_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x86;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': True,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'if_03',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'print_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_types_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_types_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_str_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_str_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_str_03',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_list_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_list_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_list_03',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_list_04',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_list_05',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_list_06',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_list_07',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_list_08',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_list_09',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_list_10',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_list_11',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_list_section',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_list_count',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_list_index',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_list_reverse',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_tuple_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_tuple_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_tuple_03',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_tuple_concat',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_dict_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_dict_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_dict_03',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_dict_04',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_dict_05',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_dict_06',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_dict_07',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_dict_08',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_dict_09',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_dict_10',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_dict_11',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_dict_bool',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_for_loop',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'modules_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x86;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'modules_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x86;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_import_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_import_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_import_03',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_import_04',
        'IMPORT_PATH': '..',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_import_05',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x86;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_math',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_numpy_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_numpy_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_numpy_03',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_numpy_04',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'elemental_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'elemental_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'elemental_03',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'elemental_04',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'elemental_05',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'elemental_06',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'elemental_07',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'elemental_08',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'elemental_09',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'elemental_10',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'elemental_11',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'elemental_12',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_random',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_os',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_builtin',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_builtin_abs',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_builtin_bool',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_builtin_pow',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_builtin_int',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_builtin_len',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_builtin_str',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_builtin_oct',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_builtin_hex',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_builtin_bin',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_builtin_float',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_builtin_str_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_builtin_round',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_builtin_divmod',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_builtin_sum',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_math1',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_math_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_math_03',
        'IMPORT_PATH': '',
        'LABELS': 'llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_pass_compare',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_c_interop_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_c_interop_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': 'test_c_interop_02b.c',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_c_interop_03',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': 'test_c_interop_03b.c',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_c_interop_04',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': 'test_c_interop_04b.c',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_c_interop_05',
        'IMPORT_PATH': '',
        'LABELS': 'llvm;c',
        'EXTRAFILES': 'test_c_interop_05b.c',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'bindc_03',
        'IMPORT_PATH': '',
        'LABELS': 'llvm;c',
        'EXTRAFILES': 'bindc_03b.c',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'bindc_05',
        'IMPORT_PATH': '',
        'LABELS': 'llvm;c',
        'EXTRAFILES': 'bindc_05b.c',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'bindc_06',
        'IMPORT_PATH': '',
        'LABELS': 'llvm;c',
        'EXTRAFILES': 'bindc_06b.c',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': True,
        'NAME': 'bindpy_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;c',
        'EXTRAFILES': 'bindpy_01_module.py',
        'EXTRA_ARGS': '--enable-cpython',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_generics_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_cmath',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_complex_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_complex_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_max_min',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_global',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_global_decl',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_integer_bitnot',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_ifexp',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_unary_minus',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_unary_plus',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_bool_binop',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_issue_518',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_03',
        'IMPORT_PATH': '',
        'LABELS': 'llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_04',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_05',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_06',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_07',
        'IMPORT_PATH': '',
        'LABELS': 'llvm;c',
        'EXTRAFILES': 'structs_07b.c',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_08',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_09',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_10',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_11',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_12',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_13',
        'IMPORT_PATH': '',
        'LABELS': 'llvm;c',
        'EXTRAFILES': 'structs_13b.c',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_14',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_15',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_16',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_17',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_18',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': 'structs_18b.c',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_19',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': 'structs_19b.c',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_20',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': 'structs_20b.c',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_21',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_22',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_23',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_24',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'structs_25',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'sizeof_01',
        'IMPORT_PATH': '',
        'LABELS': 'llvm;c',
        'EXTRAFILES': 'sizeof_01b.c',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'sizeof_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'enum_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'enum_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'enum_03',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'enum_04',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'enum_05',
        'IMPORT_PATH': '',
        'LABELS': 'llvm;c',
        'EXTRAFILES': 'enum_05b.c',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'enum_06',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'enum_07',
        'IMPORT_PATH': '..',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'union_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'union_02',
        'IMPORT_PATH': '',
        'LABELS': 'llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'union_03',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_str_to_int',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_platform',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_vars_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_version',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'logical_binop1',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'vec_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_str_comparison',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_bit_length',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'str_to_list_cast',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_sys_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'intent_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_package_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_pkg_lpdraw',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;wasm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_pkg_lnn_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_pkg_lnn_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_pkg_lpconvexhull',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'generics_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'generics_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'generics_array_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'generics_array_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'generics_array_03',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'generics_list_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_statistics',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_str_attributes',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'kwargs_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'func_inline_01',
        'IMPORT_PATH': '',
        'LABELS': 'llvm;c;wasm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'func_inline_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'func_static_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'func_static_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'func_dep_03',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'func_dep_04',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'float_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'recursive_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x64;wasm_x86',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'comp_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'bit_operations_i32',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'bit_operations_i64',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'test_argv_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'global_syms_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'global_syms_02',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'global_syms_03_b',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'global_syms_03_c',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'global_syms_04',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c;wasm;wasm_x64',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'global_syms_05',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'global_syms_06',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm;c',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'callback_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'intrinsics_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython;llvm',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    },
    {
        'FAIL': False,
        'NOFAST': False,
        'ENABLE_CPYTHON': False,
        'NAME': 'lpython_decorator_01',
        'IMPORT_PATH': '',
        'LABELS': 'cpython',
        'EXTRAFILES': '',
        'EXTRA_ARGS': '',
    }]


cmd_output = ""
cmd_error = ""


def run_cmd(cmd, cwd=None):
    global cmd_output, cmd_error
    process = sp.run(cmd, shell=True, cwd=cwd, capture_output=True, text=True)
    cmd_output += "\n" + process.stdout
    cmd_error += "\n" + process.stderr
    if process.returncode != 0:
        return False
    return True


failed_tests = []

clean_output = ""
print(f"len(all_tests): {len(all_tests)}")
for idx, test in enumerate(all_tests):
    print(f"Test {idx}: ")
    extra_options = []
    labels = test["LABELS"].split(";")
    if test['FAIL']:
        extra_options.append("FAIL")

    if "llvm" in labels:
        cmd = f"lpython --fast integration_tests/{test['NAME']}.py"
        if not run_cmd(cmd) and test['EXTRAFILES'] == '' and test['IMPORT_PATH'] == '' and (not test['FAIL']):
            failed_tests.append(test['NAME'])
            extra_options.append("NOFAST")

    clean_output += f"RUN(NAME {test['NAME']} " + \
        " ".join(extra_options) + "\n"
    clean_output += "    " + "LABELS " + " ".join(labels) + "\n"
    if test["IMPORT_PATH"]:
        clean_output += "    " + "IMPORT_PATH " + test['IMPORT_PATH'] + "\n"
    if test["EXTRAFILES"]:
        clean_output += "    " + "EXTRAFILES " + \
            " ".join(test['EXTRAFILES'].split(";")) + "\n"
    # if test["DETAILS"]:
    #     clean_output += "    " + "DETAILS \"" + test['DETAILS'] + "\"\n"
    clean_output = clean_output[:-1] + ")\n"
    clean_output += "\n"


with open("all_output.txt", "w") as cmd_output_file:
    cmd_output_file.write(cmd_output)

with open("all_stderr.txt", "w") as cmd_error_file:
    cmd_error_file.write(cmd_error)

with open("failed_tests_list.txt", "w") as failed_tests_file:
    failed_tests_file.write("\n".join(failed_tests))

with open("clean_output.txt", "w") as clean_output_file:
    clean_output_file.write(clean_output)

print("Done.")
